site_name: Redis Agent Memory Server
site_description: Give your AI agents persistent memory and context that gets smarter over time
site_url: https://redis.github.io/agent-memory-server
repo_url: https://github.com/redis/agent-memory-server
repo_name: redis/agent-memory-server
edit_uri: blob/main/docs

docs_dir: docs
exclude_docs: |
  README.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/redis/agent-memory-server
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/redislabs/agent-memory-server

  version:
    provider: mike
    default: latest

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quick-start.md
    - Installation: getting-started.md
    - Use Cases: use-cases.md

  - Developer Guide:
    - Memory Integration Patterns: memory-integration-patterns.md
    - Working Memory: working-memory.md
    - Long-term Memory: long-term-memory.md
    - Memory Extraction Strategies: memory-extraction-strategies.md
    - Memory Lifecycle: memory-lifecycle.md
    - Vector Store Backends: vector-store-backends.md
    - Authentication: authentication.md
    - Security: security-custom-prompts.md

  - Python SDK:
    - SDK Documentation: python-sdk.md
    - LangChain Integration: langchain-integration.md
    - Configuration: configuration.md

  - Examples:
    - Agent Examples: agent-examples.md

  - Advanced Topics:
    - Query Optimization: query-optimization.md
    - Recency Boost: recency-boost.md
    - Advanced Vector Store Config: vector-store-advanced.md
    - Contextual Grounding: contextual-grounding.md

  - API Reference:
    - REST API: api.md
    - MCP Server: mcp.md
    - CLI Reference: cli.md

  - Development:
    - Development Guide: development.md

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2024 <a href="https://github.com/redis"  target="_blank" rel="noopener">Redis</a>
